### ISSUE TITLE
Not a single request from the usa?

### ISSUE THREAD

**Issue by zarat** [github/gov-takedowns#15]
suspicious. hahah and in some russian notices are forks?!? why would one take down a fork while the original still remains? Any proofs on that?

**Comment by puzzle9** [comment]
nhml

**Comment by quantumpacket** [comment]
Because this whole repo is just an illusion of transparency. We all know which government calls the shots in the end.

**Comment by moidurrahaman15** [comment]
Hello sir

moidurrahaman

**Comment by wizardforcel** [comment]
post an ad: welcome to import into gitee.com

**Comment by lilydjwg** [comment]
On Thu, Feb 06, 2020 at 08:21:47AM -0800, 飞龙 wrote:
> post an ad: welcome to import into gitee.com

Where there isn't a single request from the whole world?

**Comment by zarat** [comment]
@wizardforcel it doesnt matter who spies on you - an asshole is an asshole :P

**Comment by moidurrahaman15** [comment]
Facebook Privacy Basics
https://www.facebook.com/about/basics/today-and-beyond/partnering-to-serve-you-better

moidurrahaman

**Comment by moidurrahaman15** [comment]
Helo sir

moidurrahaman

**Comment by zarat** [comment]
To stop spam i close this one :P

**Comment by moidurrahaman15** [comment]
Halo sir plessh helf my own sir

moidurrahaman
