### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by Mrmagicpie** [github/gov-takedowns#22]
Hi there,
 
I found a small typo in your README. Under the header [contributing](https://github.com/github/gov-takedowns#contributing) 

`[Contributing Guidelines](https://github.com/github/site-policy-internal/blob/master/CONTRIBUTING.md_`

should be,

`[Contributing Guidelines](https://github.com/github/site-policy-internal/blob/master/CONTRIBUTING.md)`

Hope you have a great day!

**Comment by mlinksva** [comment]
Thanks, looks like there's still an internal problem with overwriting changes to the docs as noted in #21 cc @vollmera
