### ISSUE TITLE
Beijing Network Industry Association is not a qualified entity to raise a government takedown request

### ISSUE THREAD

**Issue by WV4N** [github/gov-takedowns#25]
Hello,

I noticed the request [2021-01-22-BNIA](https://github.com/github/gov-takedowns/blob/master/China/2021/2021-01-22-BNIA.md) from the Beijing Network Industry Association asking to remove several repos that allegedly violate the laws of PRC. 

In the "[GitHub Government Takedown Policy](https://docs.github.com/en/github/site-policy/github-government-takedown-policy#what-is-a-complete-government-takedown-request)", a complete government takedown request is defined to "come from a relevant, official government agency". 

As is stated in [their self-introduction](http://m.bnia.cn/introduce/introduction.html), the Beijing Network Industry Association is a "non-profit social organization legal entity" (非营利性社会团体法人机构), which is "voluntarily initiated by ISP, ICP, IDC and major Internet industrial units in Beijing".

Furthermore, according to "*The overall plan for the decoupling of the industry associations and the administrative agencies*" ([行业协会商会与行政机关脱钩总体方案](http://www.gov.cn/zhengce/2015-07/08/content_2894118.htm)) published by the General Office of the CPC Central Committee (中共中央办公厅) and the General Office of the State Council (国务院办公厅) and "*Opinions on the implementation of the reform of decoupling the industrial associations, chambers of commerce and administrative agencies*" ([关于全面推开行业协会商会与行政机关脱钩改革的实施意见](http://www.gov.cn/xinwen/2019-06/17/content_5400947.htm)) published by the National Development and Reform Commission (国家发展改革委):

> The sponsorship, supervisor, contact, and affiliation relationship between administrative agencies (including its subordinate units) and industry associations and chambers of commerce shall be canceled. The industry associations and chambers of commerce shall be directly registered and operate independently under the law, and no longer supervised by business supervisory units." 
> (取消行政机关（包括下属单位）与行业协会商会的主办、主管、联系和挂靠关系，行业协会商会依法直接登记、独立运行，不再设置业务主管单位。)

. That is, as an industrial association, the BNIA is not affiliated in any way with the government in law.

Based on those facts and legal regulations, I suppose the BNIA is neither a subsidiary department of their government nor an "official government agency". Therefore, the BNIA turns out not to be a qualified organization with the right to raise a takedown request on behalf of the government de jure or de facto.

**Comment by kthy** [comment]
I can want to assist the government any way they want - that still doesn't make me a government agency.

**Comment by WV4N** [comment]
To subscribers and onlookers:

Please [**report**](https://github.com/contact/report-abuse?report=site-policy-bot+%28user%29) @site-policy-bot to GitHub as a potential counterfeit account so that to ask for confirming its identity.

Thanks.

**Comment by WeirdAlex03** [comment]
> To subscribers and onlookers:
> 
> Please [**report**](https://github.com/contact/report-abuse?report=site-policy-bot+%28user%29) @site-policy-bot to GitHub as a potential counterfeit account so that to ask for confirming its identity.
> 
> Thanks.

The account was created that day and the pfp is that of @hubot, the actual bot running the repo. I doubt this account is official, just an impersonation

**Comment by WV4N** [comment]
Two months passed. Still no official response - GitHub neither confirms nor denies the identity of @site-policy-bot, which is registered just following the issue, even though many (or at least @WV4N) have reported that to GitHub.

Somewhat ironically, just on Feb 25th, roughly 1 month after the issue, GitHub published [2020 Transparency Report](https://github.blog/2021-02-25-2020-transparency-report/) where "being transparent about content removal policies" is emphasized.

I especially appreciate the quality services provided by GitHub over the past years. Also, I hope communities and projects on GitHub keep prospering.

Is transparency, as is claimed in the transparency reports of the past seven years, still there?

**Comment by WV4N** [comment]
@site-policy-bot Thanks for the confirming. 

How do you recognize a social organization as a government agency according to its self-alleged "mission", despite facts listed at the beginning of the post?

If it is the proper criteria, I am going to send a government takedown request asking you to shutdown GitHub completely according to "Cybersecurity Law of the People's Republic of China" in view of the fact that GitHub are contributing to the development of anti-censorship software, with my mission be "supervising government administration agencies and the enforcement of laws”. Will GitHub accept such a request?

I think the point of "come from a relevant, official government agency" is that people could see where every government takedown request is originated and by which government department/agency it is endorsed. The government can deny the existing of such requests at any time, claiming those requests are not raised by the government in any way.

**Comment by UjuiUjuMandan** [comment]
GitHub is a shit.

**Comment by lvzx123** [comment]
> @site-policy-bot Thanks for the confirming.
> 
> How do you recognize a social organization as a government agency according to its self-alleged "mission", despite facts listed at the beginning of the post?
> 
> If it is the proper criteria, I am going to send a government takedown request asking you to shutdown GitHub completely according to "Cybersecurity Law of the People's Republic of China" since GitHub is contributing to the development of anti-censorship software, with my mission be "supervising government administration agencies and the enforcement of laws”. Will GitHub accept such a request?
> 
> I think the point of "come from a relevant, official government agency" is that people could see where every government takedown request is originated and by which government department/agency it is endorsed. Without clear criteria, the government can even deny the existence of such requests at any time, claiming those requests are not raised by the government in any way.

Btw, the "our mission" page has been disappear ed (http 404)😅
Anyway, a single claim - exactly from the unconfirmed org itself - to be admitted, is ridiculous.
